version: "3"

services:
  data-service:
    build: ./child-clinic-data/
    ports:
      - "5001:5001"

  web-service:
    build:  ./child-clinic-web/
    #      volumes:
    #        - ./child-clinic-web:/src/main/java/com.spring.childclinic/
    ports:
      - "5002:8080"
    depends_on:
      - data-service